// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVklRFuIZuPKx_NVNqRjE0dg1xpZBt6n0',
    appId: '1:55712898365:web:bcee0b93cbe6420a10f954',
    messagingSenderId: '55712898365',
    projectId: 'attend-iq-f6b6a',
    authDomain: 'attend-iq-f6b6a.firebaseapp.com',
    storageBucket: 'attend-iq-f6b6a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuCDlDUfJlFv5LXhKqAyEoKi_jOCZ-buc',
    appId: '1:55712898365:android:a692a4fe06844a0410f954',
    messagingSenderId: '55712898365',
    projectId: 'attend-iq-f6b6a',
    storageBucket: 'attend-iq-f6b6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCWsOKXk-YeMFE13tW_10HFYNCN8a8jlM',
    appId: '1:55712898365:ios:05a74462568a96ba10f954',
    messagingSenderId: '55712898365',
    projectId: 'attend-iq-f6b6a',
    storageBucket: 'attend-iq-f6b6a.firebasestorage.app',
    iosBundleId: 'com.attendpro.attendPro',
  );
}
